apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
    - name: success-rate
      successCondition: result[0] >= 0.99
      failureLimit: 3
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
          query: |
            sum(rate(response_total{dst_service="{{args.service-name}}",status_code!~"5.*"}[1m])) /
            sum(rate(response_total{dst_service="{{args.service-name}}"}[1m]))
