apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
spec:
  project: default
  source:
    path: example-service-deploy
    repoURL: http://developer:developer@gitea-http.gitea.svc.cluster.local:3000/developer/hello-service
    targetRevision: HEAD
  destination:
    namespace: default
    server: https://kubernetes.default.svc
