apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
spec:
  project: default
  source:
    path: .
    repoURL: http://developer:password@gitea-http.gitea.svc.cluster.local:3000/developer/deployment
    targetRevision: HEAD
  destination:
    namespace: default
    server: https://kubernetes.default.svc
