apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 0
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
      annotations:
        'linkerd.io/inject': 'enabled'
    spec:
      containers:
        - image: registry:5000/hello-service:argo-356e7311-7047-4103-8e59-cc472b70cd68
          name: hello
          ports:
            - containerPort: 8080
              name: hello-web
          env:
            - name: FOO
              value: "1"
