apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 0
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
      annotations:
        'linkerd.io/inject': 'enabled'
    spec:
      containers:
        - image: registry:5000/hello-service:argo-82151817-911b-4e3b-be4d-d5ab0d7daad7
          name: hello
          ports:
            - containerPort: 8080
              name: hello-web
          env:
            - name: FOO
              value: "1"
