apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hello
spec:
  entryPoints:
    - websecure
  tls: {}
  routes:
    - kind: Rule
      middlewares:
        - name: hello-l5d-dst
      match: Host(`hello.k3d.local.profitbricks.net`)
      services:
        - name: hello
          port: 80
    - kind: Rule
      middlewares:
        - name: hello-stable-l5d-dst
      match: Host(`hello-stable.k3d.local.profitbricks.net`)
      services:
        - name: hello-stable
          port: 80
    - kind: Rule
      middlewares:
        - name: hello-canary-l5d-dst
      match: Host(`hello-canary.k3d.local.profitbricks.net`)
      services:
        - name: hello-canary
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: hello-l5d-dst
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: "hello.default.svc.cluster.local:80"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: hello-stable-l5d-dst
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: "hello-stable.default.svc.cluster.local:80"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: hello-canary-l5d-dst
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: "hello-canary.default.svc.cluster.local:80"
