apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello
spec:
  replicas: 5
  strategy:
    canary:
      stableService: hello-stable
      canaryService: hello-canary
      dynamicStableScale: true
      steps:
        - setWeight: 0
        - setCanaryScale:
            replicas: 1
        - pause:
            duration: 10
        - setCanaryScale:
            matchTrafficWeight: true
        - setWeight: 20
        - pause:
            duration: 10
        - setWeight: 60
        - pause:
            duration: 10
        - setWeight: 80
        - pause:
            duration: 10
      trafficRouting:
        traefik:
          weightedTraefikServiceName: hello
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - image: registry:5000/hello-service:argo-b2313a2d-4f01-486f-bcfc-4fbbde255f74
          name: hello
          ports:
            - containerPort: 8080
              name: hello-web
